### ISSUE TITLE
[Question] Can the shared ViewModel be attached to only Fragment's lifecycle, not to activity's lifecycle

### ISSUE THREAD

**Issue by JanuszHain** [FarshadTahmasbi/Vita#3]
Hello,

As said in the title - Can the shared ViewModel be attached to only Fragment's lifecycle, not to activity's lifecycle?

I have checked readme and peeked at the code, but I am not sure if such functionality works as I described. For now it it the biggest issue for me: when I enter some fragments with steps I want to share LiveData. When I leave all of the fragments for some reason (quiting or finishing all steps) I want to see ViewModel being destroyed to keep memory free + reset data which is not needed now. When it is attached to the activity then when I re-enter steps, I will get shared ViewModel with live data that is already set, which is not the thing I want

Greetings,
Janusz

**Comment by FarshadTahmasbi** [comment]
Hi Janusz

>  Can the shared `ViewModel `be attached to only Fragment's lifecycle, not to activity's lifecycle?

The answer is YES, As a general rule, when you need a `ViewModel `to be shared between multiple `LifeCycleOwner`s, if the ViewModel does not already exist Vita creates it otherwise returns the last instance, Also it tracks owners lifecycle and keeps `ViewModel `alive while at least one owner is alive,
BTW remember to pass fragment as owner not the activity, in this way ViewModel does NOT bind to activity lifecycle, just fragments
Hope it helps
Regards
